// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTrack_processes returns the embedded CollectionSpec for track_processes.
func loadTrack_processes() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Track_processesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load track_processes: %w", err)
	}

	return spec, err
}

// loadTrack_processesObjects loads track_processes and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*track_processesObjects
//	*track_processesPrograms
//	*track_processesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrack_processesObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrack_processes()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// track_processesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type track_processesSpecs struct {
	track_processesProgramSpecs
	track_processesMapSpecs
}

// track_processesSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type track_processesProgramSpecs struct {
	TraceClose *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceOpen  *ebpf.ProgramSpec `ebpf:"trace_open"`
}

// track_processesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type track_processesMapSpecs struct {
	ProcessMap *ebpf.MapSpec `ebpf:"process_map"`
}

// track_processesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrack_processesObjects or ebpf.CollectionSpec.LoadAndAssign.
type track_processesObjects struct {
	track_processesPrograms
	track_processesMaps
}

func (o *track_processesObjects) Close() error {
	return _Track_processesClose(
		&o.track_processesPrograms,
		&o.track_processesMaps,
	)
}

// track_processesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrack_processesObjects or ebpf.CollectionSpec.LoadAndAssign.
type track_processesMaps struct {
	ProcessMap *ebpf.Map `ebpf:"process_map"`
}

func (m *track_processesMaps) Close() error {
	return _Track_processesClose(
		m.ProcessMap,
	)
}

// track_processesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrack_processesObjects or ebpf.CollectionSpec.LoadAndAssign.
type track_processesPrograms struct {
	TraceClose *ebpf.Program `ebpf:"trace_close"`
	TraceOpen  *ebpf.Program `ebpf:"trace_open"`
}

func (p *track_processesPrograms) Close() error {
	return _Track_processesClose(
		p.TraceClose,
		p.TraceOpen,
	)
}

func _Track_processesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed track_processes_bpfeb.o
var _Track_processesBytes []byte
